# Site settings
title: Moody Rd
email: blog@mrtz.org
description: A blog about machine learning.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "blog.mrtz.org" # the base hostname & protocol for your site
twitter_username: mrtz
github_username:  mrtzh

# Build settings
markdown: kramdown
